modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Crimix/bml/issues"


[[mods]] #mandatory
modId="blackdogsmoddinglibrary"
version="${file.jarVersion}"
displayName="BML"
updateJSONURL="https://raw.githubusercontent.com/Crimix/bml/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bml"
logoFile="bml-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''A library for all black_dog20's new mods'''

[[dependencies.blackdogsmoddinglibrary]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blackdogsmoddinglibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
