modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Crimix/bml/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]] #mandatory
modId="blackdogsmoddinglibrary"
version="${file.jarVersion}"
displayName="BML"
updateJSONURL="https://raw.githubusercontent.com/Crimix/bml/1.17/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bml"
logoFile="bml-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''A library for all black_dog20's new mods'''

[[dependencies.blackdogsmoddinglibrary]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blackdogsmoddinglibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
